export enum SheetName {
  CATEGORIES = 'Wzorzec kategorii',
  ACCOUTNS = 'STAN KONT',
  ALL_YEAR = 'CAŁY ROK',
  JANUARY = 'Styczeń',
  FEBRUARY = 'Luty',
  MARCH = 'Marzec',
  APRIL = 'Kwiecień',
  MAY = 'Maj',
  JUNE = 'Czerwiec',
  JULY = 'Lipiec',
  AUGUST = 'Sierpień',
  SEPTEMBER = 'Wrzesień',
  OCTOBER = 'Październik',
  NOVEMBER = 'Listopad',
  DECEMBER = 'Grudzień',
}
